cmakerun.sh 추가
DES-Terminal/DES-Explorer pull request #8
Opened 2022-08-10 15:48 UTC by shinyangdevelop

cmakerun.sh 추가했습니다. 그냥 build 폴더 만들어서 그 안에 cmake 생성하고, make 명령어 사용해서 만든 후 파일을 실행하고, 실행이 끝난 후에는 build 폴더를 지웁니다.

2022-08-10 15:49 UTC, qluana7 commented
요건 개인이 알아서 해놓는게 좋을거 같아요. 저같은 경우에는 ninja 빌드를 써서 저 빌드랑 맞지가 않아서요.

2022-08-10 16:04 UTC, Eveheeero requested changes
다음과 같은 이유로 저는 해당 사항이 수정되길 바랍니다.
- 사용자가 build 폴더를 원하지 않을 수 있음
  스크립팅을 통해, 사용자의 입력을 받아 빌드폴더를 설정하게 할 수 있지만, 현재는 그런 방안이 존재하지 않습니다.
- build폴더 안에 사용자의 중요한 데이터가 들어가 있을 수 있음
- 사용자가 sh파일을 열 수 없을 수 있음
  사용자의 컴퓨터가 sh파일을 열 수 없을 수 있습니다. CMake는 강력한 네이티브 컴파일러 도구로, 운영체제에 제한을 받지 않고 빌드를 할 수 있게 도와주는 도구입니다. 우리는 이러한 CMake의 특징을 포기하고, 운영체제에 제약을 받는 스크립트를 사용할 이유가 없습니다.
- 사용자가 make 명령어를 이용하지 않기를 원할 수 있음
  사용자는 자신 컴퓨터에 깔려있는 특정한 제네레이터 명령어를 사용하길 원할 수 있습니다.
- 스크립트 파일 안에 어떠한 명령어가 들어갈 지 알 수 없음
  해당 파일은 빌드만을 위한 것인데, 빌드를 도와주는 CMake를 놔두고, 특정 파일을 삭제하고 다운받고 실행할 수 있는 스크립트 파일을 이용할 이유가 없습니다.
- 어떤 파일을 실행해야 하는지 알 수 없음
  루트 폴더에 빌드 관련 파일이 너무 많아지면 어떤 파일을 실행해야 하는지 파악하기 어려워집니다.
- 해당 명령어는 프로그램을 빌드 후, 실행 후, 삭제하는 명령이 포함되어있습니다. 프로그램을 실행할 때마다 빌드를 새로 하는 것은 올바르지 않습니다.

2022-08-10 16:17 UTC, Eveheeero commented
만일 프로젝트가 프로그램을 빌드해서 배포하는 프로젝트였다면, 외부인 들은 프로젝트의 소스코드를 볼 수 없기 때문에, 프로그램을 빌드 만 하면 되기 때문에 큰 상관이 없었을 것 입니다. 하지만 해당 프로젝트는 공개 레포지토리로, 모든 이들이 소스코드를 볼 수 있기 때문에 개인정보가 포함될 수 있는 파일이 들어가선 안되며, 사용자가 직접 커스터마이징하여 자신의 프로그램을 빌드할 수 있게 하여야 합니다.

2022-08-11 00:34 UTC, shinyangdevelop commented
그렇군요. 그럼 이건 깃이그노어에 추가해서 저만 쓰겠습니다

2022-08-11 00:39 UTC, closed without merging